### ISSUE TITLE
Use in pointToLayer

### ISSUE THREAD

**Issue by tomchadwin** [perliedman/leaflet-multi-style#2]
How do I use this with `pointToLayer`? I have the following code:

```javascript
function style_point() {
    return {
        radius: 4.0,
        color: 'rgba(0,0,0,1.0)',
    }
}
var layer_point = new L.geoJson(json_point, {
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, style_point(feature))
    }
});
```

How can I get `L.geoJson.multiStyle` to work in this instance?

**Comment by tomchadwin** [comment]
In other words, is something like this possible:

```javascript
var layer_point = new L.geoJson.multiStyle(json_point, {
    pointToLayer: function (feature, latlng) {
        return L.circleMarker(latlng, [style_point(feature), style_point2(feature)])
    }
});
```

**Comment by perliedman** [comment]
You mean you need multiple styles for point features? I'm not currently handling that, I've actually just used this for line strings so far.

It seems totally reasonable to be able to have multiple styles for points as well, and I guess it could be implemented much like `styles` and `filters`, so that you would have `pointToLayers` or similar that is an array of functions instead.

I'll try to find time to add this, but can't promise anything. If you want to take a stab at adding it, that would of course be super.

**Comment by tomchadwin** [comment]
I'll try to have a look myself, but it's probably beyond me. Thanks so much for the lines and polygons, though. It's just what I needed!

**Comment by tomchadwin** [comment]
So are you saying it would have to be something like this:

```javascript
var layer_point = new L.geoJson.multiStyle(json_point, {
    pointToLayers: [
        function (feature, latlng) {
            return L.circleMarker(latlng, style_point(feature)),
        function (feature, latlng) {
            return L.circleMarker(latlng, style_point2(feature))]
    }
});
```

**Comment by perliedman** [comment]
Yes, exactly... one function per defined style. Possibly you could set one of the to `null`/`undefined` to make it use the default.
